const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Création du module Analytics...");

w('src/features/analytics/components/AnalyticsPanel.tsx', [
  "'use client';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "import { useStaking } from '@/features/staking/hooks/useStaking';",
  "import { PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';",
  "import { Loader, PieChart as PieIcon, BarChart2 } from 'lucide-react';",
  "",
  "const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#6B7280'];",
  "",
  "export default function AnalyticsPanel() {",
  "  const { validators } = useStaking();",
  "  ",
  "  // Fetch Supply",
  "  const { data: supplyData, isLoading: isLoadingSupply } = useQuery({",
  "    queryKey: ['luncSupply'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.amount.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  // Fetch Burned",
  "  const { data: burnData } = useQuery({",
  "    queryKey: ['luncBurned'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/balances/terra1sk06e3dyexuq4shw77y4dtt0xpqkcjm974wu5w/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.balance.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  // Fetch Staked",
  "  const { data: stakedData } = useQuery({",
  "    queryKey: ['luncStaked'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/staking/v1beta1/pool`);",
  "      return parseFloat(res.data.pool.bonded_tokens) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  // Préparation des données des Validateurs (Top 5 + Others)",
  "  const topValidators = [...validators].sort((a, b) => parseFloat(b.tokens) - parseFloat(a.tokens)).slice(0, 5);",
  "  const otherPower = validators.slice(5).reduce((sum, v) => sum + parseFloat(v.tokens), 0);",
  "  const validatorData = [",
  "    ...topValidators.map(v => ({ name: v.description.moniker.substring(0, 15), value: parseFloat(v.tokens) / 1_000_000 })),",
  "    { name: 'Others', value: otherPower / 1_000_000 }",
  "  ];",
  "",
  "  // Préparation des données de Tokenomie (en Milliards)",
  "  const tokenomicsData = [",
  "    { name: 'Staked', value: (stakedData || 0) / 1_000_000_000, fill: '#3B82F6' },",
  "    { name: 'Burned', value: (burnData || 0) / 1_000_000_000, fill: '#EF4444' },",
  "    { name: 'Circulating', value: ((supplyData || 0) - (stakedData || 0) - (burnData || 0)) / 1_000_000_000, fill: '#10B981' }",
  "  ];",
  "",
  "  return (",
  "    <div className='grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8'>",
  "      {/* Graphique 1: Validateurs */}",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'>",
  "          <PieIcon className='w-6 h-6 text-galaxy-blue' /> Répartition du Voting Power",
  "        </h3>",
  "        {validators.length === 0 ? (",
  "          <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-galaxy-blue' /></div>",
  "        ) : (",
  "          <div className='h-64 w-full'>",
  "            <ResponsiveContainer width='100%' height='100%'>",
  "              <PieChart>",
  "                <Pie data={validatorData} dataKey='value' nameKey='name' cx='50%' cy='50%' outerRadius={90} label>",
  "                  {validatorData.map((entry, index) => (",
  "                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />",
  "                  ))}",
  "                </Pie>",
  "                <Tooltip contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} />",
  "              </PieChart>",
  "            </ResponsiveContainer>",
  "          </div>",
  "        )}",
  "      </div>",
  "",
  "      {/* Graphique 2: Tokenomie */}",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'>",
  "          <BarChart2 className='w-6 h-6 text-terra-yellow' /> Tokenomie LUNC (en Milliards)",
  "        </h3>",
  "        {isLoadingSupply ? (",
  "          <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-terra-yellow' /></div>",
  "        ) : (",
  "          <div className='h-64 w-full'>",
  "            <ResponsiveContainer width='100%' height='100%'>",
  "              <BarChart data={tokenomicsData}>",
  "                <XAxis dataKey='name' stroke='#9CA3AF' fontSize={12} />",
  "                <YAxis stroke='#9CA3AF' fontSize={12} />",
  "                <Tooltip cursor={{ fill: 'rgba(255,255,255,0.05)' }} contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} />",
  "                <Bar dataKey='value' radius={[8, 8, 0, 0]} />",
  "              </BarChart>",
  "            </ResponsiveContainer>",
  "          </div>",
  "        )}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
]);

console.log('\n🎉 Module Analytics créé !');