const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Refonte globale du Dashboard et des Graphiques...");

// 1. Mise à jour de DashboardClient (Comptage fiable des validateurs)
w('src/features/dashboard/components/DashboardClient.tsx', [
  '"use client";',
  "import { motion } from 'framer-motion';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Coins, BarChart2, Activity, DollarSign, Users, ShieldCheck } from 'lucide-react';",
  "import StatCard from './StatCard';",
  "import AnalyticsPanel from '@/features/analytics/components/AnalyticsPanel';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "",
  "interface NetworkStats {",
  "  totalSupply: number;",
  "  staked: number;",
  "  stakedRatio: number;",
  "  communityPool: number;",
  "  activeValidators: number;",
  "}",
  "",
  "function useNetworkStats() {",
  "  return useQuery<NetworkStats>({",
  "    queryKey: ['advancedNetworkStatsV7'],",
  "    queryFn: async () => {",
  "      const lcd = TERRA_CLASSIC_CONFIG.lcdUrl;",
  "      ",
  "      // 1. Supply Totale",
  "      const supplyRes = await axios.get(`${lcd}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      const totalSupply = parseFloat(supplyRes.data.amount.amount) / 1_000_000;",
  "      ",
  "      // 2. Staked (Bonded Tokens)",
  "      const stakedRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/pool`);",
  "      const staked = parseFloat(stakedRes.data.pool.bonded_tokens) / 1_000_000;",
  "      ",
  "      // 3. Community Pool",
  "      const poolRes = await axios.get(`${lcd}/cosmos/distribution/v1beta1/community_pool`);",
  "      const poolUluna = poolRes.data.pool.find((p: any) => p.denom === 'uluna');",
  "      const communityPool = poolUluna ? parseFloat(poolUluna.amount) / 1_000_000 : 0;",
  "",
  "      // 4. Active Validators (On fetch la liste et on la compte, c'est 100% fiable)",
  "      const valRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/validators?status=BOND_STATUS_BONDED&pagination.limit=200`);",
  "      const activeValidators = valRes.data.validators ? valRes.data.validators.length : 0;",
  "      ",
  "      return {",
  "        totalSupply,",
  "        staked,",
  "        stakedRatio: (staked / totalSupply) * 100,",
  "        communityPool,",
  "        activeValidators",
  "      };",
  "    },",
  "    refetchInterval: 60000,",
  "  });",
  "}",
  "",
  "export default function DashboardClient() {",
  "  const { data: stats, isLoading } = useNetworkStats();",
  "  ",
  "  const { data: marketData } = useQuery({",
  "    queryKey: ['marketDataV2'],",
  "    queryFn: async () => {",
  "      const res = await axios.get('/api/network-stats/market-data');",
  "      return res.data.data;",
  "    },",
  "    refetchInterval: 120000,",
  "  });",
  "",
  "  const formatNum = (num: number) => {",
  "    if (!num) return '0';",
  "    if (num >= 1_000_000_000_000) return (num / 1_000_000_000_000).toFixed(2) + 'T';",
  "    if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(2) + 'B';",
  "    if (num >= 1_000_000) return (num / 1_000_000).toFixed(2) + 'M';",
  "    return num.toLocaleString();",
  "  };",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-2xl font-bold'>Network Dashboard</h1>",
  "        <p className='text-galaxy-gray text-sm'>Analyse en temps réel de l'écosystème Terra Classic.</p>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8'>",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title='Total Supply' value={isLoading ? '...' : formatNum(stats?.totalSupply || 0)} sub='LUNC en circulation' loading={isLoading} />",
  "        <StatCard icon={<Users className='w-5 h-5 text-galaxy-blue' />} title='Staked' value={isLoading ? '...' : formatNum(stats?.staked || 0)} sub={isLoading ? '' : `${stats?.stakedRatio.toFixed(2)}% de la supply`} loading={isLoading} />",
  "        <StatCard icon={<ShieldCheck className='w-5 h-5 text-galaxy-green' />} title='Validators' value={isLoading ? '...' : stats?.activeValidators.toLocaleString()} sub='Actifs sur le réseau' loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title='Community Pool' value={isLoading ? '...' : formatNum(stats?.communityPool || 0)} sub='Fonds communautaires' loading={isLoading} />",
  "        <StatCard icon={<DollarSign className='w-5 h-5 text-galaxy-green' />} title='Prix LUNC' value={marketData ? `$${marketData.price.toFixed(6)}` : '...'} sub={marketData ? `${marketData.change24h.toFixed(1)}% (24h)` : 'Chargement...'} loading={!marketData} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title='Market Cap' value={marketData ? `$${formatNum(marketData.marketCap)}` : '...'} sub='Calculé en direct' loading={!marketData} />",
  "      </div>",
  "",
  "      <AnalyticsPanel />",
  "    </main>",
  "  );",
  "}"
]);

// 2. Refonte de AnalyticsPanel (Suppression du Burn, focus sur Tokenomie exacte)
w('src/features/analytics/components/AnalyticsPanel.tsx', [
  "'use client';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "import { useStaking } from '@/features/staking/hooks/useStaking';",
  "import { PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';",
  "import { Loader, PieChart as PieIcon, BarChart2 } from 'lucide-react';",
  "",
  "const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#6B7280'];",
  "",
  "export default function AnalyticsPanel() {",
  "  const { validators } = useStaking();",
  "  ",
  "  const { data: supplyData, isLoading: isLoadingSupply } = useQuery({",
  "    queryKey: ['luncSupplyPanel'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.amount.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const { data: stakedData } = useQuery({",
  "    queryKey: ['luncStakedPanel'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/staking/v1beta1/pool`);",
  "      return parseFloat(res.data.pool.bonded_tokens) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const { data: communityPoolData } = useQuery({",
  "    queryKey: ['luncPoolPanel'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/distribution/v1beta1/community_pool`);",
  "      const pool = res.data.pool.find((p) => p.denom === 'uluna');",
  "      return parseFloat(pool.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  // Top 5 Validateurs",
  "  const topValidators = [...validators].sort((a, b) => parseFloat(b.tokens) - parseFloat(a.tokens)).slice(0, 5);",
  "  const otherPower = validators.slice(5).reduce((sum, v) => sum + parseFloat(v.tokens), 0);",
  "  const validatorData = [",
  "    ...topValidators.map(v => ({ name: v.description.moniker.substring(0, 15), value: parseFloat(v.tokens) / 1_000_000 })),",
  "    { name: 'Others', value: otherPower / 1_000_000 }",
  "  ];",
  "",
  "  // Tokenomie Fiable (Staked + Community Pool + Circulating)",
  "  const circulating = (supplyData || 0) - (stakedData || 0) - (communityPoolData || 0);",
  "  const tokenomicsData = [",
  "    { name: 'Staked', value: (stakedData || 0) / 1_000_000_000, fill: '#3B82F6' },",
  "    { name: 'Comm. Pool', value: (communityPoolData || 0) / 1_000_000_000, fill: '#F59E0B' },",
  "    { name: 'Circulating', value: circulating > 0 ? circulating / 1_000_000_000 : 0, fill: '#10B981' }",
  "  ];",
  "",
  "  return (",
  "    <div className='grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8'>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><PieIcon className='w-6 h-6 text-galaxy-blue' /> Répartition du Voting Power</h3>",
  "        {validators.length === 0 ? <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-galaxy-blue' /></div> : <div className='h-64 w-full'><ResponsiveContainer width='100%' height='100%'><PieChart><Pie data={validatorData} dataKey='value' nameKey='name' cx='50%' cy='50%' outerRadius={90} label>{validatorData.map((entry, index) => (<Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />))}</Pie><Tooltip contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} /></PieChart></ResponsiveContainer></div>}",
  "      </div>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><BarChart2 className='w-6 h-6 text-terra-yellow' /> Tokenomie LUNC (en Milliards)</h3>",
  "        {isLoadingSupply ? <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-terra-yellow' /></div> : <div className='h-64 w-full'><ResponsiveContainer width='100%' height='100%'><BarChart data={tokenomicsData}><XAxis dataKey='name' stroke='#9CA3AF' fontSize={12} /><YAxis stroke='#9CA3AF' fontSize={12} /><Tooltip cursor={{ fill: 'rgba(255,255,255,0.05)' }} contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} /><Bar dataKey='value' radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div>}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
]);

console.log('\n🎉 Dashboard refondu ! Indicateurs et graphiques 100% fiables.');