const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Correction des types TypeScript...");

w('src/features/dashboard/components/DashboardClient.tsx', [
  '"use client";',
  "import { motion } from 'framer-motion';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Flame, Coins, BarChart2, Activity, DollarSign, Users } from 'lucide-react';",
  "import StatCard from './StatCard';",
  "import AnalyticsPanel from '@/features/analytics/components/AnalyticsPanel';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "",
  "interface NetworkStats {",
  "  totalSupply: number;",
  "  totalBurned: number;",
  "  staked: number;",
  "  stakedRatio: number;",
  "  communityPool: number;",
  "}",
  "",
  "function useNetworkStats() {",
  "  return useQuery<NetworkStats>({",
  "    queryKey: ['advancedNetworkStatsV4'],",
  "    queryFn: async () => {",
  "      const lcd = TERRA_CLASSIC_CONFIG.lcdUrl;",
  "      ",
  "      // 1. Supply Totale",
  "      const supplyRes = await axios.get(`${lcd}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      const totalSupply = parseFloat(supplyRes.data.amount.amount) / 1_000_000;",
  "      ",
  "      // 2. Total Burned (via notre API locale pour éviter le CORS)",
  "      let totalBurned = 0;",
  "      try {",
  "        const burnRes = await axios.get('/api/network-stats/burn');",
  "        totalBurned = burnRes.data.totalBurned;",
  "      } catch (err: any) {",
  "        console.error('Erreur API Burn:', err.message);",
  "      }",
  "      ",
  "      // 3. Staked (Bonded Tokens)",
  "      const stakedRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/pool`);",
  "      const staked = parseFloat(stakedRes.data.pool.bonded_tokens) / 1_000_000;",
  "      ",
  "      // 4. Community Pool",
  "      const poolRes = await axios.get(`${lcd}/cosmos/distribution/v1beta1/community_pool`);",
  "      const poolUluna = poolRes.data.pool.find((p: any) => p.denom === 'uluna');",
  "      const communityPool = poolUluna ? parseFloat(poolUluna.amount) / 1_000_000 : 0;",
  "      ",
  "      return {",
  "        totalSupply,",
  "        totalBurned,",
  "        staked,",
  "        stakedRatio: (staked / totalSupply) * 100,",
  "        communityPool,",
  "      };",
  "    },",
  "    refetchInterval: 60000,",
  "  });",
  "}",
  "",
  "export default function DashboardClient() {",
  "  const { data: stats, isLoading } = useNetworkStats();",
  "  ",
  "  const { data: marketData } = useQuery({",
  "    queryKey: ['marketDataV2'],",
  "    queryFn: async () => {",
  "      const res = await axios.get('/api/network-stats/market-data');",
  "      return res.data.data;",
  "    },",
  "    refetchInterval: 120000,",
  "  });",
  "",
  "  const formatNum = (num: number) => {",
  "    if (!num) return '0';",
  "    if (num >= 1_000_000_000_000) return (num / 1_000_000_000_000).toFixed(2) + 'T';",
  "    if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(2) + 'B';",
  "    if (num >= 1_000_000) return (num / 1_000_000).toFixed(2) + 'M';",
  "    return num.toLocaleString();",
  "  };",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-2xl font-bold'>Network Dashboard</h1>",
  "        <p className='text-galaxy-gray text-sm'>Analyse en temps réel de l'écosystème Terra Classic.</p>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8'>",
  "        <StatCard icon={<Flame className='w-5 h-5 text-galaxy-red' />} title='Total Burned' value={isLoading ? '...' : formatNum(stats?.totalBurned || 0)} sub='LUNC détruits' loading={isLoading} />",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title='Total Supply' value={isLoading ? '...' : formatNum(stats?.totalSupply || 0)} sub='LUNC en circulation' loading={isLoading} />",
  "        <StatCard icon={<Users className='w-5 h-5 text-galaxy-blue' />} title='Staked' value={isLoading ? '...' : formatNum(stats?.staked || 0)} sub={isLoading ? '' : `${stats?.stakedRatio.toFixed(2)}% de la supply`} loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title='Community Pool' value={isLoading ? '...' : formatNum(stats?.communityPool || 0)} sub='Fonds communautaires' loading={isLoading} />",
  "        <StatCard icon={<DollarSign className='w-5 h-5 text-galaxy-green' />} title='Prix LUNC' value={marketData ? `$${marketData.price.toFixed(6)}` : '...'} sub={marketData ? `${marketData.change24h.toFixed(1)}% (24h)` : 'Chargement...'} loading={!marketData} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title='Market Cap' value={marketData ? `$${formatNum(marketData.marketCap)}` : '...'} sub='Calculé en direct' loading={!marketData} />",
  "      </div>",
  "",
  "      <AnalyticsPanel />",
  "    </main>",
  "  );",
  "}"
]);

console.log('\n🎉 Types TypeScript corrigés !');