const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Réorganisation finale du Dashboard et création de la page DFC...");

// 1. Mise à jour du Dashboard (Focus Analytics + Total Burned corrigé)
w('src/features/dashboard/components/DashboardClient.tsx', [
  '"use client";',
  "import { motion } from 'framer-motion';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Flame, Coins, BarChart2, Activity } from 'lucide-react';",
  "import StatCard from './StatCard';",
  "import AnalyticsPanel from '@/features/analytics/components/AnalyticsPanel';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "",
  "export default function DashboardClient() {",
  "  // Fetch Stats Réseau (Block height, Staked)",
  "  const { data: stats, isLoading } = useQuery({",
  "    queryKey: ['networkStats'],",
  "    queryFn: async () => {",
  "      const res = await axios.get('/api/network-stats');",
  "      return res.data.data;",
  "    },",
  "    refetchInterval: 60000,",
  "  });",
  "",
  "  // Fetch Total Burned directement depuis la LCD",
  "  const { data: burnData } = useQuery({",
  "    queryKey: ['totalBurnedLunc'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/balances/terra1sk06e3dyexuq4shw77y4dtt0xpqkcjm974wu5w/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.balance.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const formatNumber = (num) => {",
  "    if (!num) return '0';",
  "    if (num >= 1_000_000_000_000) return (num / 1_000_000_000_000).toFixed(2) + 'T';",
  "    if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(2) + 'B';",
  "    if (num >= 1_000_000) return (num / 1_000_000).toFixed(2) + 'M';",
  "    return num.toLocaleString();",
  "  };",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-2xl font-bold'>Network Dashboard</h1>",
  "        <p className='text-galaxy-gray text-sm'>Analyse en temps réel de l'écosystème Terra Classic.</p>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8'>",
  "        <StatCard icon={<Flame className='w-5 h-5 text-galaxy-red' />} title='Total Burned' value={formatNumber(burnData || 0)} sub='Adresse Burn' loading={isLoading} />",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title='Staked' value={isLoading ? '...' : formatNumber(stats?.staked || 0)} sub={isLoading ? '' : `${stats?.stakingRatio}% de la supply`} loading={isLoading} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title='Market Cap' value={isLoading ? '...' : '$592.4M'} sub='Source: CoinGecko' loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title='Block Height' value={isLoading ? '...' : Number(stats?.blockHeight).toLocaleString()} sub='Réseau en direct' loading={isLoading} />",
  "      </div>",
  "",
  "      <AnalyticsPanel />",
  "    </main>",
  "  );",
  "}"
]);

// 2. Création de la page DFC Hub dédiée
w('src/app/dfc/page.tsx', [
  '"use client";',
  "import dynamic from 'next/dynamic';",
  "import { motion } from 'framer-motion';",
  "import { useWallet } from '@/features/wallet/hooks/useWallet';",
  "import { useDFC } from '@/features/wallet/hooks/useDFC';",
  "import { Wallet as WalletIcon } from 'lucide-react';",
  "",
  "const WalletPanel = dynamic(() => import('@/features/dashboard/components/WalletPanel'), { ssr: false });",
  "const StakingPanel = dynamic(() => import('@/features/dashboard/components/StakingPanel'), { ssr: false });",
  "",
  "export default function DFCPage() {",
  "  const { address, isConnected } = useWallet();",
  "  const { dfcBalance, stakedBalance, pendingRewards, pendingFees, claimRewards, claimFees, stakeDFC, unstakeDFC, isProcessing, txHash, error } = useDFC();",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-3xl font-bold mb-2'>DFLunc Protocol Hub</h1>",
  "        <p className='text-galaxy-gray text-sm'>Gérez votre DFC, vos rewards et votre staking DFLunc.</p>",
  "      </motion.div>",
  "",
  "      {!isConnected ? (",
  "        <div className='glass-card rounded-3xl p-12 text-center'>",
  "          <div className='w-20 h-20 rounded-full bg-galaxy-blue/20 flex items-center justify-center mx-auto mb-6'>",
  "            <WalletIcon className='w-10 h-10 text-galaxy-blue' />",
  "          </div>",
  "          <h2 className='text-3xl font-bold mb-4'>Mon Portefeuille DFC</h2>",
  "          <p className='text-galaxy-gray text-lg mb-8 max-w-xl mx-auto'>Connectez votre wallet pour accéder à vos tokens DFC, vos rewards de staking, et interagir avec les contrats.</p>",
  "        </div>",
  "      ) : (",
  "        <div className='space-y-6'>",
  "          <WalletPanel address={address} dfcBalance={dfcBalance} stakedBalance={stakedBalance} pendingRewards={pendingRewards} pendingFees={pendingFees} isProcessing={isProcessing} txHash={txHash} txError={error} onClaimRewards={claimRewards} onClaimFees={claimFees} />",
  "          <StakingPanel dfcBalance={dfcBalance} stakedBalance={stakedBalance} isProcessing={isProcessing} onStake={stakeDFC} onUnstake={unstakeDFC} />",
  "        </div>",
  "      )}",
  "    </main>",
  "  );",
  "}"
]);

// 3. Étoffer l'AnalyticsPanel avec un 3ème graphique (Community Pool)
w('src/features/analytics/components/AnalyticsPanel.tsx', [
  "'use client';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "import { useStaking } from '@/features/staking/hooks/useStaking';",
  "import { PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';",
  "import { Loader, PieChart as PieIcon, BarChart2, Coins } from 'lucide-react';",
  "",
  "const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#6B7280'];",
  "",
  "export default function AnalyticsPanel() {",
  "  const { validators } = useStaking();",
  "  ",
  "  const { data: supplyData, isLoading: isLoadingSupply } = useQuery({",
  "    queryKey: ['luncSupply'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.amount.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const { data: burnData } = useQuery({",
  "    queryKey: ['luncBurned'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/balances/terra1sk06e3dyexuq4shw77y4dtt0xpqkcjm974wu5w/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.balance.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const { data: stakedData } = useQuery({",
  "    queryKey: ['luncStaked'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/staking/v1beta1/pool`);",
  "      return parseFloat(res.data.pool.bonded_tokens) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  // Nouveau: Community Pool",
  "  const { data: communityPoolData } = useQuery({",
  "    queryKey: ['luncPool'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/distribution/v1beta1/community_pool`);",
  "      const pool = res.data.pool.find(p => p.denom === 'uluna');",
  "      return parseFloat(pool.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const topValidators = [...validators].sort((a, b) => parseFloat(b.tokens) - parseFloat(a.tokens)).slice(0, 5);",
  "  const otherPower = validators.slice(5).reduce((sum, v) => sum + parseFloat(v.tokens), 0);",
  "  const validatorData = [",
  "    ...topValidators.map(v => ({ name: v.description.moniker.substring(0, 15), value: parseFloat(v.tokens) / 1_000_000 })),",
  "    { name: 'Others', value: otherPower / 1_000_000 }",
  "  ];",
  "",
  "  const tokenomicsData = [",
  "    { name: 'Staked', value: (stakedData || 0) / 1_000_000_000, fill: '#3B82F6' },",
  "    { name: 'Burned', value: (burnData || 0) / 1_000_000_000, fill: '#EF4444' },",
  "    { name: 'Circulating', value: ((supplyData || 0) - (stakedData || 0) - (burnData || 0)) / 1_000_000_000, fill: '#10B981' }",
  "  ];",
  "",
  "  const distributionData = [",
  "    { name: 'Community Pool', value: (communityPoolData || 0) / 1_000_000_000, fill: '#F59E0B' },",
  "    { name: 'Staked', value: (stakedData || 0) / 1_000_000_000, fill: '#3B82F6' },",
  "    { name: 'Burned', value: (burnData || 0) / 1_000_000_000, fill: '#EF4444' },",
  "  ];",
  "",
  "  return (",
  "    <div className='grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8'>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><PieIcon className='w-6 h-6 text-galaxy-blue' /> Répartition du Voting Power</h3>",
  "        {validators.length === 0 ? <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-galaxy-blue' /></div> : <div className='h-64 w-full'><ResponsiveContainer width='100%' height='100%'><PieChart><Pie data={validatorData} dataKey='value' nameKey='name' cx='50%' cy='50%' outerRadius={90} label>{validatorData.map((entry, index) => (<Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />))}</Pie><Tooltip contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} /></PieChart></ResponsiveContainer></div>}",
  "      </div>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><BarChart2 className='w-6 h-6 text-terra-yellow' /> Tokenomie LUNC (en Milliards)</h3>",
  "        {isLoadingSupply ? <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-terra-yellow' /></div> : <div className='h-64 w-full'><ResponsiveContainer width='100%' height='100%'><BarChart data={tokenomicsData}><XAxis dataKey='name' stroke='#9CA3AF' fontSize={12} /><YAxis stroke='#9CA3AF' fontSize={12} /><Tooltip cursor={{ fill: 'rgba(255,255,255,0.05)' }} contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} /><Bar dataKey='value' radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div>}",
  "      </div>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><Coins className='w-6 h-6 text-galaxy-green' /> Distribution de la Supply (en Milliards)</h3>",
  "        {isLoadingSupply ? <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-galaxy-green' /></div> : <div className='h-64 w-full'><ResponsiveContainer width='100%' height='100%'><BarChart data={distributionData} layout='vertical'><XAxis type='number' stroke='#9CA3AF' fontSize={12} /><YAxis dataKey='name' type='category' stroke='#9CA3AF' fontSize={12} width={80}/><Tooltip cursor={{ fill: 'rgba(255,255,255,0.05)' }} contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} /><Bar dataKey='value' radius={[0, 8, 8, 0]} /></BarChart></ResponsiveContainer></div>}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
]);

// 4. Mise à jour de la Navbar avec l'onglet DFC Hub
w('src/components/layout/Navbar.tsx', [
  "import Link from 'next/link';",
  "import Logo from '@/components/Logo';",
  "import { Search, Bell, Moon } from 'lucide-react';",
  "import ConnectWalletButton from '@/features/wallet/components/ConnectWalletButton';",
  "",
  "export default function Navbar() {",
  "  return (",
  "    <header className='fixed top-6 left-1/2 -translate-x-1/2 z-50 w-[95%] max-w-7xl'>",
  "      <nav className='glass-card rounded-[32px] flex flex-wrap items-center justify-between gap-4 px-6 py-4 shadow-[0_24px_120px_rgba(0,0,0,0.18)]'>",
  "        <Link href='/' className='flex items-center gap-3'>",
  "          <Logo size={36} />",
  "          <span className='font-bold text-lg tracking-tight text-galaxy-white'>LUNC <span className='text-terra-yellow'>TERMINAL</span></span>",
  "        </Link>",
  "        <div className='hidden xl:flex gap-8 text-sm font-medium text-galaxy-gray-muted'>",
  "          <Link href='/' className='hover:text-galaxy-white transition-colors'>Dashboard</Link>",
  "          <Link href='/dfc' className='hover:text-galaxy-white transition-colors'>DFC Hub</Link>",
  "          <Link href='/burn-tracker' className='hover:text-galaxy-white transition-colors'>Burn</Link>",
  "          <Link href='/validateurs' className='hover:text-galaxy-white transition-colors'>Validators</Link>",
  "          <Link href='/governance' className='hover:text-galaxy-white transition-colors'>Governance</Link>",
  "          <Link href='/actualites' className='hover:text-galaxy-white transition-colors'>News</Link>",
  "          <Link href='/settings' className='hover:text-galaxy-white transition-colors'>Settings</Link>",
  "        </div>",
  "        <div className='flex items-center gap-3'>",
  "          <button className='text-galaxy-gray-muted hover:text-galaxy-white transition-colors rounded-full p-2 bg-white/5 border border-white/10' aria-label='Recherche'><Search className='w-5 h-5' /></button>",
  "          <button className='relative text-galaxy-gray-muted hover:text-galaxy-white transition-colors rounded-full p-2 bg-white/5 border border-white/10' aria-label='Notifications'><Bell className='w-5 h-5' /><span className='absolute top-1 right-1 w-2 h-2 bg-galaxy-red rounded-full shadow-[0_0_12px_rgba(255,92,112,0.35)]'></span></button>",
  "          <button className='text-galaxy-gray-muted hover:text-galaxy-white transition-colors rounded-full p-2 bg-white/5 border border-white/10' aria-label='Mode sombre'><Moon className='w-5 h-5' /></button>",
  "          <ConnectWalletButton />",
  "        </div>",
  "      </nav>",
  "    </header>",
  "  );",
  "}"
]);

console.log('\n🎉 Réorganisation terminée ! Le Dashboard est centré sur les Analytics, et le DFC a sa propre page !');