const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Création du Mode Simple / Expert...");

// 1. Création du Store Zustand
w('src/store/settingsStore.ts', [
  "import { create } from 'zustand';",
  "import { persist } from 'zustand/middleware';",
  "",
  "interface SettingsState {",
  "  isExpertMode: boolean;",
  "  toggleExpertMode: () => void;",
  "}",
  "",
  "export const useSettingsStore = create<SettingsState>()(",
  "  persist(",
  "    (set) => ({",
  "      isExpertMode: false,",
  "      toggleExpertMode: () => set((state) => ({ isExpertMode: !state.isExpertMode })),",
  "    }),",
  "    { name: 'lunc-terminal-settings' }",
  "  )",
  ");"
]);

// 2. Création de la page Settings
w('src/app/settings/page.tsx', [
  '"use client";',
  "",
  "import { motion } from 'framer-motion';",
  "import { useSettingsStore } from '@/store/settingsStore';",
  "import { Settings as SettingsIcon, Eye, EyeOff } from 'lucide-react';",
  "",
  "export default function SettingsPage() {",
  "  const { isExpertMode, toggleExpertMode } = useSettingsStore();",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-4xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-3xl font-bold mb-2 flex items-center gap-3'>",
  "          <SettingsIcon className='w-8 h-8 text-terra-yellow' /> Paramètres",
  "        </h1>",
  "        <p className='text-galaxy-gray text-sm'>Personnalisez votre expérience LUNC Terminal.</p>",
  "      </motion.div>",
  "",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <div className='flex flex-col md:flex-row justify-between items-start md:items-center gap-4 p-6 bg-space-bg/50 rounded-2xl'>",
  "          <div className='flex items-center gap-4'>",
  "            {isExpertMode ? <Eye className='w-6 h-6 text-galaxy-blue' /> : <EyeOff className='w-6 h-6 text-galaxy-gray' />}",
  "            <div>",
  "              <h2 className='text-xl font-bold text-galaxy-white'>Mode Expert</h2>",
  "              <p className='text-sm text-galaxy-gray'>",
  "                {isExpertMode ? 'Affiche les données techniques (adresses de contrats, denoms).' : 'Masque les données blockchain complexes.'}",
  "              </p>",
  "            </div>",
  "          </div>",
  "          ",
  "          <button onClick={toggleExpertMode} className={`relative w-16 h-8 rounded-full transition-colors ${isExpertMode ? 'bg-galaxy-blue' : 'bg-galaxy-gray/30'}`}>",
  "            <span className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${isExpertMode ? 'translate-x-9' : 'translate-x-1'}`} />",
  "          </button>",
  "        </div>",
  "      </div>",
  "    </main>",
  "  );",
  "}"
]);

// 3. Mise à jour de WalletPanel
w('src/features/dashboard/components/WalletPanel.tsx', [
  "import { Wallet, CheckCircle2, AlertCircle } from 'lucide-react';",
  "import { useSettingsStore } from '@/store/settingsStore';",
  "",
  "interface WalletPanelProps {",
  "  address: string | null;",
  "  dfcBalance: string;",
  "  stakedBalance: string;",
  "  pendingRewards: string;",
  "  pendingFees: string;",
  "  isProcessing: boolean;",
  "  txHash: string | null;",
  "  txError: string | null;",
  "  onClaimRewards: () => void;",
  "  onClaimFees: () => void;",
  "}",
  "",
  "export default function WalletPanel({",
  "  address, dfcBalance, stakedBalance, pendingRewards, pendingFees,",
  "  isProcessing, txHash, txError, onClaimRewards, onClaimFees",
  "}: WalletPanelProps) {",
  "  const { isExpertMode } = useSettingsStore();",
  "",
  "  return (",
  "    <div className='glass-card rounded-3xl p-8'>",
  "      <h2 className='text-xl font-bold mb-6 flex items-center gap-3'>",
  "        <Wallet className='w-6 h-6 text-terra-yellow' /> Portefeuille & Rewards",
  "      </h2>",
  "      <div className='grid grid-cols-1 md:grid-cols-4 gap-6'>",
  "        <div className='bg-space-bg/50 p-6 rounded-2xl'>",
  "          <p className='text-galaxy-gray text-xs uppercase tracking-wider mb-2'>DFC Disponible</p>",
  "          <p className='text-2xl font-bold text-terra-yellow'>{dfcBalance}</p>",
  "        </div>",
  "        <div className='bg-space-bg/50 p-6 rounded-2xl'>",
  "          <p className='text-galaxy-gray text-xs uppercase tracking-wider mb-2'>DFC Staké</p>",
  "          <p className='text-2xl font-bold text-galaxy-blue'>{stakedBalance}</p>",
  "        </div>",
  "        <div className='bg-space-bg/50 p-6 rounded-2xl flex flex-col justify-between'>",
  "          <div className='flex justify-between mb-4'>",
  "            <div>",
  "              <p className='text-galaxy-gray text-xs uppercase tracking-wider mb-1'>Rewards DFC</p>",
  "              <p className='text-xl font-bold text-galaxy-green'>{pendingRewards}</p>",
  "            </div>",
  "            <div className='text-right'>",
  "              <p className='text-galaxy-gray text-xs uppercase tracking-wider mb-1'>Rewards USTC</p>",
  "              <p className='text-xl font-bold text-galaxy-blue'>{pendingFees}</p>",
  "            </div>",
  "          </div>",
  "          <div className='flex gap-2'>",
  "            <button onClick={onClaimRewards} disabled={isProcessing || pendingRewards === '0'} className={`btn-premium flex-1 px-4 py-2 rounded-xl text-sm font-bold ${isProcessing || pendingRewards === '0' ? 'opacity-50 cursor-not-allowed' : ''}`}>{isProcessing ? '...' : 'Claim DFC'}</button>",
  "            <button onClick={onClaimFees} disabled={isProcessing || pendingFees === '0'} className={`bg-galaxy-blue/20 text-galaxy-blue border border-galaxy-blue/30 flex-1 px-4 py-2 rounded-xl text-sm font-bold hover:bg-galaxy-blue/30 ${isProcessing || pendingFees === '0' ? 'opacity-50 cursor-not-allowed' : ''}`}>{isProcessing ? '...' : 'Claim USTC'}</button>",
  "          </div>",
  "        </div>",
  "        <div className='bg-space-bg/50 p-6 rounded-2xl flex flex-col justify-center items-center text-center'>",
  "          <p className='text-galaxy-gray text-xs uppercase tracking-wider mb-2'>Adresse</p>",
  "          {isExpertMode ? (",
  "            <p className='font-mono text-xs text-galaxy-white break-all'>{address}</p>",
  "          ) : (",
  "            <p className='font-mono text-sm text-galaxy-white'>{address ? `${address.slice(0, 10)}...${address.slice(-6)}` : 'Non connecté'}</p>",
  "          )}",
  "        </div>",
  "      </div>",
  "      {txHash && (",
  "        <div className='mt-6 bg-galaxy-green/10 border border-galaxy-green/30 rounded-xl p-4 flex items-center gap-3 text-galaxy-green'>",
  "          <CheckCircle2 className='w-5 h-5 flex-shrink-0' />",
  "          <p className='text-sm'>Transaction réussie ! Hash: {txHash.slice(0, 20)}...</p>",
  "        </div>",
  "      )}",
  "      {txError && (",
  "        <div className='mt-6 bg-galaxy-red/10 border border-galaxy-red/30 rounded-xl p-4 flex items-center gap-3 text-galaxy-red'>",
  "          <AlertCircle className='w-5 h-5 flex-shrink-0' />",
  "          <p className='text-sm'>{txError}</p>",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "}"
]);

console.log('\n🎉 Mode Simple / Expert créé avec succès !');