const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Traduction du Dashboard complet...");

// 1. Mise à jour du dictionnaire de traduction
w('src/lib/translations.ts', [
  "import { Language } from '@/store/languageStore';",
  "",
  "export const translations = {",
  "  fr: {",
  "    nav: { dashboard: 'Dashboard', dfc: 'DFC Hub', burn: 'Burn', validators: 'Validators', governance: 'Governance', news: 'News', settings: 'Settings' },",
  "    wallet: { connect: 'Connect Wallet', disconnect: 'Déconnexion' },",
  "    dashboard: { title: 'Network Dashboard', subtitle: 'Analyse en temps réel de l\\'écosystème Terra Classic.' },",
  "    stats: { totalSupply: 'Total Supply', staked: 'Staked', validators: 'Validators', communityPool: 'Community Pool', price: 'Prix LUNC', marketCap: 'Market Cap', supplySub: 'LUNC', stakedSub: 'de la supply', validatorsSub: 'Actifs', poolSub: 'Fonds communautaires', liveSub: 'Live' },",
  "    analytics: { votingPower: 'Répartition du Voting Power', tokenomics: 'Tokenomie LUNC (en Milliards)' }",
  "  },",
  "  en: {",
  "    nav: { dashboard: 'Dashboard', dfc: 'DFC Hub', burn: 'Burn', validators: 'Validators', governance: 'Governance', news: 'News', settings: 'Settings' },",
  "    wallet: { connect: 'Connect Wallet', disconnect: 'Disconnect' },",
  "    dashboard: { title: 'Network Dashboard', subtitle: 'Real-time analysis of the Terra Classic ecosystem.' },",
  "    stats: { totalSupply: 'Total Supply', staked: 'Staked', validators: 'Validators', communityPool: 'Community Pool', price: 'Price LUNC', marketCap: 'Market Cap', supplySub: 'LUNC', stakedSub: 'of supply', validatorsSub: 'Active', poolSub: 'Community funds', liveSub: 'Live' },",
  "    analytics: { votingPower: 'Voting Power Distribution', tokenomics: 'LUNC Tokenomics (in Billions)' }",
  "  },",
  "  zh: {",
  "    nav: { dashboard: '仪表盘', dfc: 'DFC中心', burn: '销毁', validators: '验证节点', governance: '治理', news: '新闻', settings: '设置' },",
  "    wallet: { connect: '连接钱包', disconnect: '断开连接' },",
  "    dashboard: { title: '网络仪表盘', subtitle: 'Terra Classic 生态系统的实时分析。' },",
  "    stats: { totalSupply: '总供应量', staked: '质押量', validators: '验证节点', communityPool: '社区池', price: 'LUNC 价格', marketCap: '市值', supplySub: 'LUNC', stakedSub: '占总供应', validatorsSub: '活跃', poolSub: '社区资金', liveSub: '实时' },",
  "    analytics: { votingPower: '投票权分布', tokenomics: 'LUNC 代币经济学（十亿）' }",
  "  }",
  "};",
  "",
  "export const useTranslation = (lang: Language) => {",
  "  return translations[lang];",
  "};"
]);

// 2. Mise à jour de DashboardClient (Titres des cartes traduits)
w('src/features/dashboard/components/DashboardClient.tsx', [
  '"use client";',
  "import { motion } from 'framer-motion';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Coins, BarChart2, Activity, DollarSign, Users, ShieldCheck } from 'lucide-react';",
  "import StatCard from './StatCard';",
  "import AnalyticsPanel from '@/features/analytics/components/AnalyticsPanel';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "import { useLanguageStore } from '@/store/languageStore';",
  "import { useTranslation } from '@/lib/translations';",
  "",
  "interface NetworkStats { totalSupply: number; staked: number; stakedRatio: number; communityPool: number; activeValidators: number; }",
  "",
  "function useNetworkStats() {",
  "  return useQuery<NetworkStats>({",
  "    queryKey: ['advancedNetworkStatsV12'],",
  "    queryFn: async () => {",
  "      const lcd = TERRA_CLASSIC_CONFIG.lcdUrl;",
  "      const supplyRes = await axios.get(`${lcd}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      const totalSupply = parseFloat(supplyRes.data.amount.amount) / 1_000_000;",
  "      const stakedRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/pool`);",
  "      const staked = parseFloat(stakedRes.data.pool.bonded_tokens) / 1_000_000;",
  "      const poolRes = await axios.get(`${lcd}/cosmos/distribution/v1beta1/community_pool`);",
  "      const poolUluna = poolRes.data.pool.find((p: any) => p.denom === 'uluna');",
  "      const communityPool = poolUluna ? parseFloat(poolUluna.amount) / 1_000_000 : 0;",
  "      const valRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/validators?status=BOND_STATUS_BONDED&pagination.limit=200`);",
  "      const activeValidators = valRes.data.validators ? valRes.data.validators.length : 0;",
  "      return { totalSupply, staked, stakedRatio: (staked / totalSupply) * 100, communityPool, activeValidators };",
  "    },",
  "    refetchInterval: 60000,",
  "  });",
  "}",
  "",
  "function useMarketData() {",
  "  return useQuery({",
  "    queryKey: ['marketDataApiLocal'],",
  "    queryFn: async () => { const res = await axios.get('/api/price'); return res.data; },",
  "    refetchInterval: 120000,",
  "  });",
  "}",
  "",
  "export default function DashboardClient() {",
  "  const { data: stats, isLoading } = useNetworkStats();",
  "  const { data: marketData } = useMarketData();",
  "  const lang = useLanguageStore((state) => state.lang);",
  "  const t = useTranslation(lang);",
  "",
  "  const formatNum = (num: number) => {",
  "    if (!num) return '0';",
  "    if (num >= 1_000_000_000_000) return (num / 1_000_000_000_000).toFixed(2) + 'T';",
  "    if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(2) + 'B';",
  "    if (num >= 1_000_000) return (num / 1_000_000).toFixed(2) + 'M';",
  "    return num.toLocaleString();",
  "  };",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-2xl font-bold'>{t.dashboard.title}</h1>",
  "        <p className='text-galaxy-gray text-sm'>{t.dashboard.subtitle}</p>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8'>",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title={t.stats.totalSupply} value={isLoading ? '...' : formatNum(stats?.totalSupply || 0)} sub={t.stats.supplySub} loading={isLoading} />",
  "        <StatCard icon={<Users className='w-5 h-5 text-galaxy-blue' />} title={t.stats.staked} value={isLoading ? '...' : formatNum(stats?.staked || 0)} sub={isLoading ? '' : `${stats?.stakedRatio.toFixed(2)}% ${t.stats.stakedSub}`} loading={isLoading} />",
  "        <StatCard icon={<ShieldCheck className='w-5 h-5 text-galaxy-green' />} title={t.stats.validators} value={isLoading ? '...' : stats?.activeValidators.toLocaleString()} sub={t.stats.validatorsSub} loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title={t.stats.communityPool} value={isLoading ? '...' : formatNum(stats?.communityPool || 0)} sub={t.stats.poolSub} loading={isLoading} />",
  "        <StatCard icon={<DollarSign className='w-5 h-5 text-galaxy-green' />} title={t.stats.price} value={marketData ? `$${marketData.price.toFixed(6)}` : '...'} sub={marketData ? `${marketData.change24h.toFixed(1)}%` : '...'} loading={!marketData} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title={t.stats.marketCap} value={marketData && stats ? `$${formatNum(marketData.price * stats.totalSupply)}` : '...'} sub={t.stats.liveSub} loading={!marketData || !stats} />",
  "      </div>",
  "",
  "      <AnalyticsPanel />",
  "    </main>",
  "  );",
  "}"
]);

// 3. Mise à jour de AnalyticsPanel (Titres des graphiques traduits)
w('src/features/analytics/components/AnalyticsPanel.tsx', [
  "'use client';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "import { useStaking } from '@/features/staking/hooks/useStaking';",
  "import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';",
  "import { Loader, PieChart as PieIcon } from 'lucide-react';",
  "import { useLanguageStore } from '@/store/languageStore';",
  "import { useTranslation } from '@/lib/translations';",
  "",
  "const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#6B7280'];",
  "",
  "export default function AnalyticsPanel() {",
  "  const { validators } = useStaking();",
  "  const lang = useLanguageStore((state) => state.lang);",
  "  const t = useTranslation(lang);",
  "  ",
  "  const { data: supplyData, isLoading: isLoadingSupply } = useQuery({",
  "    queryKey: ['luncSupplyPanel'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      return parseFloat(res.data.amount.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const { data: stakedData } = useQuery({",
  "    queryKey: ['luncStakedPanel'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/staking/v1beta1/pool`);",
  "      return parseFloat(res.data.pool.bonded_tokens) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const { data: communityPoolData } = useQuery({",
  "    queryKey: ['luncPoolPanel'],",
  "    queryFn: async () => {",
  "      const res = await axios.get(`${TERRA_CLASSIC_CONFIG.lcdUrl}/cosmos/distribution/v1beta1/community_pool`);",
  "      const pool = res.data.pool.find((p) => p.denom === 'uluna');",
  "      return parseFloat(pool.amount) / 1_000_000;",
  "    }",
  "  });",
  "",
  "  const topValidators = [...validators].sort((a, b) => parseFloat(b.tokens) - parseFloat(a.tokens)).slice(0, 5);",
  "  const otherPower = validators.slice(5).reduce((sum, v) => sum + parseFloat(v.tokens), 0);",
  "  const validatorData = [",
  "    ...topValidators.map(v => ({ name: v.description.moniker.substring(0, 15), value: parseFloat(v.tokens) / 1_000_000 })),",
  "    { name: 'Others', value: otherPower / 1_000_000 }",
  "  ];",
  "",
  "  const circulating = (supplyData || 0) - (stakedData || 0) - (communityPoolData || 0);",
  "  const tokenomicsData = [",
  "    { name: 'Circulating', value: circulating > 0 ? circulating / 1_000_000_000 : 0 },",
  "    { name: 'Staked', value: (stakedData || 0) / 1_000_000_000 },",
  "    { name: 'Comm. Pool', value: (communityPoolData || 0) / 1_000_000_000 }",
  "  ];",
  "",
  "  return (",
  "    <div className='grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8'>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><PieIcon className='w-6 h-6 text-galaxy-blue' /> {t.analytics.votingPower}</h3>",
  "        {validators.length === 0 ? (",
  "          <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-galaxy-blue' /></div>",
  "        ) : (",
  "          <div className='h-64 w-full'>",
  "            <ResponsiveContainer width='100%' height='100%'>",
  "              <PieChart>",
  "                <Pie data={validatorData} dataKey='value' nameKey='name' cx='50%' cy='50%' outerRadius={80} innerRadius={40} minAngle={5} label>",
  "                  {validatorData.map((entry, index) => (",
  "                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />",
  "                  ))}",
  "                </Pie>",
  "                <Tooltip contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} />",
  "                <Legend wrapperStyle={{ fontSize: '12px' }} />",
  "              </PieChart>",
  "            </ResponsiveContainer>",
  "          </div>",
  "        )}",
  "      </div>",
  "      <div className='glass-card rounded-3xl p-8'>",
  "        <h3 className='text-xl font-bold mb-6 flex items-center gap-3'><PieIcon className='w-6 h-6 text-terra-yellow' /> {t.analytics.tokenomics}</h3>",
  "        {isLoadingSupply ? (",
  "          <div className='flex justify-center py-12'><Loader className='w-8 h-8 animate-spin text-terra-yellow' /></div>",
  "        ) : (",
  "          <div className='h-64 w-full'>",
  "            <ResponsiveContainer width='100%' height='100%'>",
  "              <PieChart>",
  "                <Pie data={tokenomicsData} dataKey='value' nameKey='name' cx='50%' cy='50%' outerRadius={80} innerRadius={40} minAngle={10} label>",
  "                  <Cell fill='#10B981' />",
  "                  <Cell fill='#3B82F6' />",
  "                  <Cell fill='#F59E0B' />",
  "                </Pie>",
  "                <Tooltip contentStyle={{ background: '#0B1022', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }} />",
  "                <Legend wrapperStyle={{ fontSize: '12px' }} />",
  "              </PieChart>",
  "            </ResponsiveContainer>",
  "          </div>",
  "        )}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
]);

console.log('\n🎉 Dashboard traduit !');