const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Création de la route API Prix robuste...");

// 1. Route API locale pour le prix (contourne les blocages Vercel/CORS)
w('src/app/api/price/route.ts', [
  "import { NextResponse } from 'next/server';",
  "import axios from 'axios';",
  "",
  "export async function GET() {",
  "  // Valeur de secours si toutes les APIs plantent",
  "  const FALLBACK_PRICE = 0.000049;",
  "  const FALLBACK_CHANGE = 0.5;",
  "",
  "  try {",
  "    // On tente Binance (fonctionne très bien côté serveur sur Vercel)",
  "    const res = await axios.get('https://api.binance.com/api/v3/ticker/24hr?symbol=LUNCUSDT', { timeout: 5000 });",
  "    const price = parseFloat(res.data.lastPrice);",
  "    const change24h = parseFloat(res.data.priceChangePercent);",
  "    if (price > 0) return NextResponse.json({ price, change24h });",
  "  } catch (e) { console.error('Binance API failed:', e.message); }",
  "  ",
  "  try {",
  "    // Fallback sur CoinGecko",
  "    const res = await axios.get('https://api.coingecko.com/api/v3/simple/price?ids=terra-classic&vs_currencies=usd&include_24hr_change=true', { timeout: 5000 });",
  "    const price = res.data['terra-classic'].usd;",
  "    const change24h = res.data['terra-classic'].usd_24h_change;",
  "    if (price > 0) return NextResponse.json({ price, change24h });",
  "  } catch (e) { console.error('CoinGecko API failed:', e.message); }",
  "",
  "  // Si tout échoue, on renvoie le prix de secours pour ne pas casser l'UI",
  "  return NextResponse.json({ price: FALLBACK_PRICE, change24h: FALLBACK_CHANGE, fallback: true });",
  "}"
]);

// 2. Mise à jour du Dashboard pour utiliser l'API locale
w('src/features/dashboard/components/DashboardClient.tsx', [
  '"use client";',
  "import { motion } from 'framer-motion';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Coins, BarChart2, Activity, DollarSign, Users, ShieldCheck } from 'lucide-react';",
  "import StatCard from './StatCard';",
  "import AnalyticsPanel from '@/features/analytics/components/AnalyticsPanel';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "",
  "interface NetworkStats {",
  "  totalSupply: number;",
  "  staked: number;",
  "  stakedRatio: number;",
  "  communityPool: number;",
  "  activeValidators: number;",
  "}",
  "",
  "function useNetworkStats() {",
  "  return useQuery<NetworkStats>({",
  "    queryKey: ['advancedNetworkStatsV11'],",
  "    queryFn: async () => {",
  "      const lcd = TERRA_CLASSIC_CONFIG.lcdUrl;",
  "      const supplyRes = await axios.get(`${lcd}/cosmos/bank/v1beta1/supply/by_denom?denom=uluna`);",
  "      const totalSupply = parseFloat(supplyRes.data.amount.amount) / 1_000_000;",
  "      const stakedRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/pool`);",
  "      const staked = parseFloat(stakedRes.data.pool.bonded_tokens) / 1_000_000;",
  "      const poolRes = await axios.get(`${lcd}/cosmos/distribution/v1beta1/community_pool`);",
  "      const poolUluna = poolRes.data.pool.find((p: any) => p.denom === 'uluna');",
  "      const communityPool = poolUluna ? parseFloat(poolUluna.amount) / 1_000_000 : 0;",
  "      const valRes = await axios.get(`${lcd}/cosmos/staking/v1beta1/validators?status=BOND_STATUS_BONDED&pagination.limit=200`);",
  "      const activeValidators = valRes.data.validators ? valRes.data.validators.length : 0;",
  "      return { totalSupply, staked, stakedRatio: (staked / totalSupply) * 100, communityPool, activeValidators };",
  "    },",
  "    refetchInterval: 60000,",
  "  });",
  "}",
  "",
  "function useMarketData() {",
  "  return useQuery({",
  "    queryKey: ['marketDataApiLocal'],",
  "    queryFn: async () => {",
  "      // On appelle notre route API locale pour éviter les blocages CORS",
  "      const res = await axios.get('/api/price');",
  "      return res.data;",
  "    },",
  "    refetchInterval: 120000,",
  "  });",
  "}",
  "",
  "export default function DashboardClient() {",
  "  const { data: stats, isLoading } = useNetworkStats();",
  "  const { data: marketData } = useMarketData();",
  "",
  "  const formatNum = (num: number) => {",
  "    if (!num) return '0';",
  "    if (num >= 1_000_000_000_000) return (num / 1_000_000_000_000).toFixed(2) + 'T';",
  "    if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(2) + 'B';",
  "    if (num >= 1_000_000) return (num / 1_000_000).toFixed(2) + 'M';",
  "    return num.toLocaleString();",
  "  };",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <h1 className='text-2xl font-bold'>Network Dashboard</h1>",
  "        <p className='text-galaxy-gray text-sm'>Analyse en temps réel de l'écosystème Terra Classic.</p>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8'>",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title='Total Supply' value={isLoading ? '...' : formatNum(stats?.totalSupply || 0)} sub='LUNC en circulation' loading={isLoading} />",
  "        <StatCard icon={<Users className='w-5 h-5 text-galaxy-blue' />} title='Staked' value={isLoading ? '...' : formatNum(stats?.staked || 0)} sub={isLoading ? '' : `${stats?.stakedRatio.toFixed(2)}% de la supply`} loading={isLoading} />",
  "        <StatCard icon={<ShieldCheck className='w-5 h-5 text-galaxy-green' />} title='Validators' value={isLoading ? '...' : stats?.activeValidators.toLocaleString()} sub='Actifs sur le réseau' loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title='Community Pool' value={isLoading ? '...' : formatNum(stats?.communityPool || 0)} sub='Fonds communautaires' loading={isLoading} />",
  "        <StatCard icon={<DollarSign className='w-5 h-5 text-galaxy-green' />} title='Prix LUNC' value={marketData ? `$${marketData.price.toFixed(6)}` : '...'} sub={marketData ? `${marketData.change24h.toFixed(1)}% (24h)` : 'Chargement...'} loading={!marketData} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title='Market Cap' value={marketData && stats ? `$${formatNum(marketData.price * stats.totalSupply)}` : '...'} sub='Calculé en direct' loading={!marketData || !stats} />",
  "      </div>",
  "",
  "      <AnalyticsPanel />",
  "    </main>",
  "  );",
  "}"
]);

console.log('\n🎉 Route API Prix créée et Dashboard mis à jour !');