const fs = require('fs');
const path = require('path');

const w = (p, lines) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const content = lines.join('\n');
  fs.writeFileSync(p, content, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Mise à jour du Dashboard avec les Analytics...");

w('src/features/dashboard/components/DashboardClient.tsx', [
  '"use client";',
  "import { motion } from 'framer-motion';",
  "import { useWallet } from '@/features/wallet/hooks/useWallet';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Flame, Vote, Coins, BarChart2, Wallet as WalletIcon, Activity } from 'lucide-react';",
  "import { useDFC } from '@/features/wallet/hooks/useDFC';",
  "import StatCard from './StatCard';",
  "import ActionCard from './ActionCard';",
  "import WalletPanel from './WalletPanel';",
  "import StakingPanel from './StakingPanel';",
  "import AnalyticsPanel from '@/features/analytics/components/AnalyticsPanel';",
  "",
  "function useNetworkStats() {",
  "  return useQuery({",
  "    queryKey: ['networkStats'],",
  "    queryFn: async () => {",
  "      const res = await axios.get('/api/network-stats');",
  "      return res.data.data;",
  "    },",
  "    refetchInterval: 60000,",
  "  });",
  "}",
  "",
  "export default function DashboardClient() {",
  "  const { address, isConnected } = useWallet();",
  "  const { data: stats, isLoading } = useNetworkStats();",
  "  const { dfcBalance, stakedBalance, pendingRewards, pendingFees, claimRewards, claimFees, stakeDFC, unstakeDFC, isProcessing, txHash, error } = useDFC();",
  "",
  "  const formatNumber = (num) => {",
  "    if (!num) return '0';",
  "    if (num >= 1_000_000_000_000) return (num / 1_000_000_000_000).toFixed(2) + 'T';",
  "    if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(2) + 'B';",
  "    if (num >= 1_000_000) return (num / 1_000_000).toFixed(2) + 'M';",
  "    return num.toLocaleString();",
  "  };",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <div className='flex flex-col md:flex-row justify-between items-start md:items-center gap-6'>",
  "          <div>",
  "            <div className='flex items-center gap-3 mb-2'>",
  "              <div className='w-12 h-12 rounded-full bg-gradient-to-br from-terra-yellow to-yellow-600 flex items-center justify-center text-space-bg font-extrabold text-xl'>L</div>",
  "              <div>",
  "                <h1 className='text-2xl font-bold'>DFLUNC Terminal v2</h1>",
  "                <p className='text-galaxy-gray text-sm'>Stats Réseau & Portefeuille DFC</p>",
  "              </div>",
  "            </div>",
  "          </div>",
  "        </div>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8'>",
  "        <StatCard icon={<Flame className='w-5 h-5 text-galaxy-red' />} title='Total Burned' value={isLoading ? '...' : formatNumber(stats?.totalBurned || 0)} sub='Source: Terra LCD' loading={isLoading} />",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title='Staked' value={isLoading ? '...' : formatNumber(stats?.staked || 0)} sub={isLoading ? '' : `${stats?.stakingRatio}% de la supply`} loading={isLoading} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title='Market Cap' value={isLoading ? '...' : '$592.4M'} sub='Source: CoinGecko' loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title='Block Height' value={isLoading ? '...' : Number(stats?.blockHeight).toLocaleString()} sub='Réseau en direct' loading={isLoading} />",
  "      </div>",
  "",
  "      <AnalyticsPanel />",
  "",
  "      {!isConnected ? (",
  "        <div className='glass-card rounded-3xl p-12 text-center'>",
  "          <div className='w-20 h-20 rounded-full bg-galaxy-blue/20 flex items-center justify-center mx-auto mb-6'>",
  "            <WalletIcon className='w-10 h-10 text-galaxy-blue' />",
  "          </div>",
  "          <h2 className='text-3xl font-bold mb-4'>Mon Portefeuille DFC</h2>",
  "          <p className='text-galaxy-gray text-lg mb-8 max-w-xl mx-auto'>",
  "            Connectez votre wallet (en haut à droite) pour accéder à vos tokens DFC, vos rewards de staking, et interagir avec les contrats.",
  "          </p>",
  "        </div>",
  "      ) : (",
  "        <div className='space-y-6'>",
  "          <WalletPanel address={address} dfcBalance={dfcBalance} stakedBalance={stakedBalance} pendingRewards={pendingRewards} pendingFees={pendingFees} isProcessing={isProcessing} txHash={txHash} txError={error} onClaimRewards={claimRewards} onClaimFees={claimFees} />",
  "          <StakingPanel dfcBalance={dfcBalance} stakedBalance={stakedBalance} isProcessing={isProcessing} onStake={stakeDFC} onUnstake={unstakeDFC} />",
  "          <div className='grid grid-cols-2 md:grid-cols-4 gap-4'>",
  "            <ActionCard icon={<Coins className='w-8 h-8 text-terra-yellow mb-4' />} title='Staking' desc='Déléguer & Réclamer' />",
  "            <ActionCard icon={<Vote className='w-8 h-8 text-terra-yellow mb-4' />} title='Governance' desc='Voter & Propositions' />",
  "            <ActionCard icon={<Flame className='w-8 h-8 text-terra-yellow mb-4' />} title='Burn' desc='Tracker & Historique' />",
  "            <ActionCard icon={<BarChart2 className='w-8 h-8 text-terra-yellow mb-4' />} title='Marché' desc='Prix & Analytics' />",
  "          </div>",
  "        </div>",
  "      )}",
  "    </main>",
  "  );",
  "}"
]);

console.log('\n🎉 Dashboard mis à jour avec les graphiques !');