const fs = require('fs');
const path = require('path');

const w = (p, c) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, c, 'utf8');
  console.log('✅ ' + p);
};

console.log("🚀 Réparation complète de l'application...");

w('src/config/chains.ts', [
  "export const TERRA_CLASSIC_CONFIG = {",
  "  chainId: 'columbus-5',",
  "  chainName: 'Terra Classic',",
  "  rpcUrl: 'https://terra-classic-rpc.publicnode.com',",
  "  lcdUrl: 'https://terra-classic-lcd.publicnode.com',",
  "  denom: 'uluna',",
  "  symbol: 'LUNC',",
  "};"
].join('\n'));

w('src/config/contracts.ts', [
  "export const DFLUNC_HUB_CONTRACT = 'terra1eewgymwqqp0wcdllmz36xaank8lj3fcylzj3wx';",
  "export const DFC_TOKEN_CONTRACT = 'terra1r9laq5788d36gx8jkayln3g5szg4ql0nmccs';",
  "export const DFC_STAKING_CONTRACT = 'terra1eewgymwqqp0wcdllmz36xaank8lj3fcylzj3wx';"
].join('\n'));

w('src/services/DFCService.ts', [
  "import { CosmWasmClient } from '@cosmjs/cosmwasm-stargate';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "import { DFC_TOKEN_CONTRACT, DFC_STAKING_CONTRACT } from '@/config/contracts';",
  "",
  "let client = null;",
  "async function getClient() {",
  "  if (!client) client = await CosmWasmClient.connect(TERRA_CLASSIC_CONFIG.rpcUrl);",
  "  return client;",
  "}",
  "",
  "export const DFCService = {",
  "  async getBalance(address) {",
  "    try {",
  "      const c = await getClient();",
  "      const res = await c.queryContractSmart(DFC_TOKEN_CONTRACT, { balance: { address } });",
  "      return (Number(res.balance) / 1000000).toFixed(2);",
  "    } catch { return '0'; }",
  "  },",
  "  async getStakerInfo(address) {",
  "    try {",
  "      const c = await getClient();",
  "      let staked = '0', rewards = '0', fees = '0';",
  "      try { const r = await c.queryContractSmart(DFC_STAKING_CONTRACT, { get_acc_withdrawable_stake: { user_address: address } }); staked = r.amount || '0'; } catch {}",
  "      try { const r = await c.queryContractSmart(DFC_STAKING_CONTRACT, { get_unclaimed_rewards: { user_address: address } }); rewards = r.amount || '0'; } catch {}",
  "      try { const r = await c.queryContractSmart(DFC_STAKING_CONTRACT, { get_unclaimed_fees: { user_address: address } }); fees = r.amount || '0'; } catch {}",
  "      return { staked, rewards, fees };",
  "    } catch { return { staked: '0', rewards: '0', fees: '0' }; }",
  "  }",
  "};"
].join('\n'));

w('src/features/wallet/services/wallet.service.ts', [
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "",
  "export class WalletService {",
  "  constructor(controller, connected) {",
  "    this.controller = controller;",
  "    this.connected = connected;",
  "  }",
  "",
  "  getAddress() {",
  "    return this.connected ? Object.values(this.connected.addresses || {})[0] : undefined;",
  "  }",
  "",
  "  async executeTransaction(contractAddress, msg) {",
  "    if (!this.controller || !this.controller.post) throw new Error('Wallet non connecté');",
  "    const address = this.getAddress();",
  "    if (!address) throw new Error('Adresse non disponible');",
  "",
  "    const executeMsg = {",
  "      contract: contractAddress,",
  "      msg: Buffer.from(JSON.stringify(msg)).toString('base64'),",
  "      funds: [],",
  "    };",
  "",
  "    try {",
  "      const result = await this.controller.post({",
  "        msgs: [executeMsg],",
  "        gasAdjustment: '1.5',",
  "        chainID: TERRA_CLASSIC_CONFIG.chainId,",
  "      });",
  "      if (result && result.result && result.result.txhash) return result.result.txhash;",
  "      throw new Error('Transaction échouée');",
  "    } catch (err) { throw new Error(err.message || 'Erreur de broadcast'); }",
  "  }",
  "}"
].join('\n'));

w('src/features/wallet/components/WalletProviderClient.tsx', [
  "'use client';",
  "import { WalletProvider } from '@terra-money/wallet-kit';",
  "import { ReactNode } from 'react';",
  "import { TERRA_CLASSIC_CONFIG } from '@/config/chains';",
  "",
  "// @ts-ignore",
  "const networksConfig = {",
  "  [TERRA_CLASSIC_CONFIG.chainId]: {",
  "    chainID: TERRA_CLASSIC_CONFIG.chainId,",
  "    URL: TERRA_CLASSIC_CONFIG.lcdUrl,",
  "    gasAdjustment: '1.5',",
  "    gasPrices: '0.15uluna',",
  "    prefix: 'terra',",
  "    isClassic: true,",
  "  },",
  "};",
  "",
  "export default function WalletProviderClient({ children }) {",
  "  // @ts-ignore",
  "  return <WalletProvider defaultNetworks={networksConfig}>{children}</WalletProvider>;",
  "}"
].join('\n'));

w('src/app/providers.tsx', [
  "'use client';",
  "import { QueryClient, QueryClientProvider } from '@tanstack/react-query';",
  "import { useState } from 'react';",
  "import dynamic from 'next/dynamic';",
  "",
  "const WalletProviderClient = dynamic(() => import('@/features/wallet/components/WalletProviderClient'), { ssr: false });",
  "",
  "export function Providers({ children }) {",
  "  const [queryClient] = useState(() => new QueryClient());",
  "  return (",
  "    <QueryClientProvider client={queryClient}>",
  "      <WalletProviderClient>{children}</WalletProviderClient>",
  "    </QueryClientProvider>",
  "  );",
  "}"
].join('\n'));

w('src/features/wallet/hooks/useWallet.ts', [
  "'use client';",
  "import { useWallet as useTerraWallet } from '@terra-money/wallet-kit';",
  "export function useWallet() {",
  "  const w = useTerraWallet();",
  "  return {",
  "    controller: w.walletController,",
  "    connected: w.connectedWallet,",
  "    status: w.status,",
  "    availableWallets: w.availableWallets,",
  "    connect: w.connectWallet,",
  "    disconnect: w.disconnectWallet,",
  "    isConnected: w.isConnected,",
  "    address: w.address || null,",
  "  };",
  "}"
].join('\n'));

w('src/features/wallet/hooks/useDFC.ts', [
  "'use client';",
  "import { useState } from 'react';",
  "import { useQuery, useQueryClient } from '@tanstack/react-query';",
  "import { DFCService } from '@/services/DFCService';",
  "import { useWallet } from '@/features/wallet/hooks/useWallet';",
  "import { WalletService } from '@/features/wallet/services/wallet.service';",
  "import { DFC_TOKEN_CONTRACT, DFC_STAKING_CONTRACT } from '@/config/contracts';",
  "",
  "export function useDFC() {",
  "  const { controller, connected, isConnected, address } = useWallet();",
  "  const queryClient = useQueryClient();",
  "  const [isProcessing, setIsProcessing] = useState(false);",
  "  const [txHash, setTxHash] = useState(null);",
  "  const [error, setError] = useState(null);",
  "",
  "  const { data } = useQuery({",
  "    queryKey: ['dfcData', address],",
  "    queryFn: async () => {",
  "      if (!address) return null;",
  "      const balance = await DFCService.getBalance(address);",
  "      const info = await DFCService.getStakerInfo(address);",
  "      return {",
  "        dfcBalance: balance,",
  "        stakedBalance: (Number(info.staked || 0) / 1000000).toFixed(2),",
  "        pendingRewards: (Number(info.rewards || 0) / 1000000).toFixed(2),",
  "        pendingFees: (Number(info.fees || 0) / 1000000).toFixed(2),",
  "      };",
  "    },",
  "    enabled: isConnected && !!address,",
  "    refetchInterval: 30000,",
  "  });",
  "",
  "  const executeTransaction = async (contractAddress, msg) => {",
  "    if (!isConnected || !address || !controller) { setError('Wallet non connecté'); return false; }",
  "    setIsProcessing(true); setError(null); setTxHash(null);",
  "    try {",
  "      const walletService = new WalletService(controller, connected);",
  "      const hash = await walletService.executeTransaction(contractAddress, msg);",
  "      setTxHash(hash);",
  "      return true;",
  "    } catch (err) { setError(err.message || 'Échec'); return false; }",
  "    finally { setIsProcessing(false); }",
  "  };",
  "",
  "  const refreshData = () => queryClient.invalidateQueries({ queryKey: ['dfcData', address] });",
  "",
  "  const claimRewards = async () => {",
  "    if (await executeTransaction(DFC_STAKING_CONTRACT, { claim_rewards: { receipt_address: address } })) setTimeout(refreshData, 5000);",
  "  };",
  "  const claimFees = async () => {",
  "    if (await executeTransaction(DFC_STAKING_CONTRACT, { claim_fees: {} })) setTimeout(refreshData, 5000);",
  "  };",
  "  const stakeDFC = async (amount) => {",
  "    const amt = Math.floor(amount * 1000000).toString();",
  "    if (await executeTransaction(DFC_TOKEN_CONTRACT, { increase_allowance: { spender: DFC_STAKING_CONTRACT, amount: amt, expires: { never: {} } } })) {",
  "      if (await executeTransaction(DFC_STAKING_CONTRACT, { stake: { amount: amt } })) setTimeout(refreshData, 5000);",
  "    }",
  "  };",
  "  const unstakeDFC = async (amount) => {",
  "    const amt = Math.floor(amount * 1000000).toString();",
  "    if (await executeTransaction(DFC_STAKING_CONTRACT, { unstake: { amount: amt } })) setTimeout(refreshData, 5000);",
  "  };",
  "",
  "  return { dfcBalance: data?.dfcBalance || '0', stakedBalance: data?.stakedBalance || '0', pendingRewards: data?.pendingRewards || '0', pendingFees: data?.pendingFees || '0', claimRewards, claimFees, stakeDFC, unstakeDFC, isProcessing, txHash, error };",
  "}"
].join('\n'));

w('src/features/wallet/components/ConnectWalletButton.tsx', [
  "'use client';",
  "import { useWallet } from '../hooks/useWallet';",
  "import { Wallet, LogOut } from 'lucide-react';",
  "",
  "export default function ConnectWalletButton() {",
  "  const { address, isConnected, connect, disconnect } = useWallet();",
  "  if (isConnected && address) {",
  "    return (",
  "      <div className='flex items-center gap-2'>",
  "        <div className='hidden md:flex items-center gap-2 bg-galaxy-blue/10 border border-galaxy-blue/30 px-4 py-2 rounded-xl text-sm font-bold text-galaxy-blue'>",
  "          <Wallet className='w-4 h-4' /> {address.slice(0, 6)}...{address.slice(-4)}",
  "        </div>",
  "        <button onClick={disconnect} className='bg-galaxy-red/20 hover:bg-galaxy-red/40 text-galaxy-red px-4 py-2 rounded-xl text-sm font-bold flex items-center gap-2'>",
  "          <LogOut className='w-4 h-4' /> Déconnexion",
  "        </button>",
  "      </div>",
  "    );",
  "  }",
  "  return (",
  "    <button onClick={connect} className='btn-premium px-5 py-2 rounded-xl text-sm font-bold flex items-center gap-2'>",
  "      <Wallet className='w-4 h-4' /> Connect Wallet",
  "    </button>",
  "  );",
  "}"
].join('\n'));

w('src/features/dashboard/components/DashboardClient.tsx', [
  "\"use client\";",
  "import { motion } from 'framer-motion';",
  "import { useWallet } from '@/features/wallet/hooks/useWallet';",
  "import { useQuery } from '@tanstack/react-query';",
  "import axios from 'axios';",
  "import { Flame, Vote, Coins, BarChart2, Wallet as WalletIcon, Activity } from 'lucide-react';",
  "import { useDFC } from '@/features/wallet/hooks/useDFC';",
  "import StatCard from './StatCard';",
  "import ActionCard from './ActionCard';",
  "import WalletPanel from './WalletPanel';",
  "import StakingPanel from './StakingPanel';",
  "",
  "export default function DashboardClient() {",
  "  const { address, isConnected } = useWallet();",
  "  const { data: stats, isLoading } = useQuery({ queryKey: ['netStats'], queryFn: async () => (await axios.get('/api/network-stats')).data.data, refetchInterval: 60000 });",
  "  const { dfcBalance, stakedBalance, pendingRewards, pendingFees, claimRewards, claimFees, stakeDFC, unstakeDFC, isProcessing, txHash, error } = useDFC();",
  "",
  "  const formatNumber = (num) => num >= 1000000000 ? (num / 1000000000).toFixed(2) + 'B' : num.toLocaleString();",
  "",
  "  return (",
  "    <main className='min-h-screen relative container mx-auto px-6 py-8 max-w-7xl'>",
  "      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className='glass-card rounded-3xl p-8 mb-6'>",
  "        <div className='flex flex-col md:flex-row justify-between items-start md:items-center gap-6'>",
  "          <div>",
  "            <h1 className='text-2xl font-bold'>DFLUNC Terminal v2</h1>",
  "            <p className='text-galaxy-gray text-sm'>Stats Réseau & Portefeuille DFC</p>",
  "          </div>",
  "        </div>",
  "      </motion.div>",
  "",
  "      <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8'>",
  "        <StatCard icon={<Flame className='w-5 h-5 text-galaxy-red' />} title='Total Burned' value={isLoading ? '...' : formatNumber(stats?.totalBurned || 0)} sub='Source: Terra LCD' loading={isLoading} />",
  "        <StatCard icon={<Coins className='w-5 h-5 text-terra-yellow' />} title='Staked' value={isLoading ? '...' : formatNumber(stats?.staked || 0)} sub='Ratio' loading={isLoading} />",
  "        <StatCard icon={<BarChart2 className='w-5 h-5 text-galaxy-blue' />} title='Market Cap' value='$592.4M' sub='Source: CoinGecko' loading={isLoading} />",
  "        <StatCard icon={<Activity className='w-5 h-5 text-galaxy-green' />} title='Block Height' value={isLoading ? '...' : Number(stats?.blockHeight).toLocaleString()} sub='Réseau en direct' loading={isLoading} />",
  "      </div>",
  "",
  "      {!isConnected ? (",
  "        <div className='glass-card rounded-3xl p-12 text-center'>",
  "          <div className='w-20 h-20 rounded-full bg-galaxy-blue/20 flex items-center justify-center mx-auto mb-6'>",
  "            <WalletIcon className='w-10 h-10 text-galaxy-blue' />",
  "          </div>",
  "          <h2 className='text-3xl font-bold mb-4'>Mon Portefeuille DFC</h2>",
  "          <p className='text-galaxy-gray text-lg mb-8 max-w-xl mx-auto'>Connectez votre wallet (en haut à droite) pour accéder à vos tokens DFC, vos rewards de staking, et interagir avec les contrats.</p>",
  "        </div>",
  "      ) : (",
  "        <div className='space-y-6'>",
  "          <WalletPanel address={address} dfcBalance={dfcBalance} stakedBalance={stakedBalance} pendingRewards={pendingRewards} pendingFees={pendingFees} isProcessing={isProcessing} txHash={txHash} txError={error} onClaimRewards={claimRewards} onClaimFees={claimFees} />",
  "          <StakingPanel dfcBalance={dfcBalance} stakedBalance={stakedBalance} isProcessing={isProcessing} onStake={stakeDFC} onUnstake={unstakeDFC} />",
  "          <div className='grid grid-cols-2 md:grid-cols-4 gap-4'>",
  "            <ActionCard icon={<Coins className='w-8 h-8 text-terra-yellow mb-4' />} title='Staking' desc='Déléguer & Réclamer' />",
  "            <ActionCard icon={<Vote className='w-8 h-8 text-terra-yellow mb-4' />} title='Governance' desc='Voter & Propositions' />",
  "            <ActionCard icon={<Flame className='w-8 h-8 text-terra-yellow mb-4' />} title='Burn' desc='Tracker & Historique' />",
  "            <ActionCard icon={<BarChart2 className='w-8 h-8 text-terra-yellow mb-4' />} title='Marché' desc='Prix & Analytics' />",
  "          </div>",
  "        </div>",
  "      )}",
  "    </main>",
  "  );",
  "}"
].join('\n'));

if (fs.existsSync('src/hooks/useDFC.ts')) fs.unlinkSync('src/hooks/useDFC.ts');

console.log('\n🎉 Application réinitialisée avec succès !');